/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Desplegables;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        int Nivel = obtenerNivelUsuario();  // Llamada al método que obtiene el nivel

        // Condicional para cambiar la visibilidad de los menús
        if (Nivel == 0) {
            menMantenimiento.setVisible(false); 
            menProcesos.setVisible(false); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menMantenimiento = new javax.swing.JMenu();
        itmUsuario = new javax.swing.JMenuItem();
        itmCatalogo = new javax.swing.JMenuItem();
        menMovimiento = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menProcesos = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(37, 109, 123));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(171, 40));

        menMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-mantenimiento-32.png"))); // NOI18N
        menMantenimiento.setText("Mantenimientos");

        itmUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-grupo-de-usuario-32.png"))); // NOI18N
        itmUsuario.setText("Usuarios");
        itmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmUsuarioActionPerformed(evt);
            }
        });
        menMantenimiento.add(itmUsuario);

        itmCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-catalogo-externo-inmobiliario-esquema-bartama-esquema-64-bartama-grafico-32.png"))); // NOI18N
        itmCatalogo.setText("Catalogo de cuenta");
        itmCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCatalogoActionPerformed(evt);
            }
        });
        menMantenimiento.add(itmCatalogo);

        jMenuBar1.add(menMantenimiento);

        menMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-negocio-32.png"))); // NOI18N
        menMovimiento.setText("Movimiento");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-tarjeta-32.png"))); // NOI18N
        jMenuItem3.setText("Transacciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menMovimiento.add(jMenuItem3);

        jMenuBar1.add(menMovimiento);

        menProcesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-administración-de-explotación-comercial-32.png"))); // NOI18N
        menProcesos.setText("Procesos");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-diario-32.png"))); // NOI18N
        jMenuItem4.setText("Cierre Diario por Fechas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menProcesos.add(jMenuItem4);

        jMenuBar1.add(menProcesos);
        menProcesos.getAccessibleContext().setAccessibleDescription("");

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-encuentra-hombre-usuario-32.png"))); // NOI18N
        jMenu12.setText("Consultas");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-catalogo-externo-inmobiliario-esquema-bartama-esquema-64-bartama-grafico-32.png"))); // NOI18N
        jMenuItem7.setText("Catalogo de cuenta");
        jMenu12.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-fecha-32.png"))); // NOI18N
        jMenuItem8.setText("Transacciones por fecha");
        jMenu12.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-documento-32.png"))); // NOI18N
        jMenuItem9.setText("Transacciones por documento");
        jMenu12.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-archivo-lista-de-piezas-32.png"))); // NOI18N
        jMenuItem10.setText("Transacciones por tipo de documento");
        jMenu12.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-balanza-32.png"))); // NOI18N
        jMenuItem11.setText("Balanza general");
        jMenu12.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-analítica-32.png"))); // NOI18N
        jMenuItem12.setText("Resumen de gastos generales");
        jMenu12.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-signo-de-dinero-32.png"))); // NOI18N
        jMenuItem13.setText("Estado de Ganancias y Perdidas");
        jMenu12.add(jMenuItem13);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private int obtenerNivelUsuario() {
       int nivel = -1;  // Valor predeterminado en caso de que no se encuentre el nivel
//        try {
//            File archivo = new File("C:\\Users\\admin\\Desktop\\Usuario.txt");
//            Scanner scanner = new Scanner(archivo);
//
//            // Leer línea por línea
//            while (scanner.hasNextLine()) {
//                String linea = scanner.nextLine();
//                Scanner lineaScanner = new Scanner(linea);
//                lineaScanner.useDelimiter("\\s*;\\s*");  // Delimitador por ";"
//
//                // Leer los valores de la línea (suponiendo el formato: usuario;contraseña;nivel;nombre;apellido)
//                String log = lineaScanner.next();
//                String pass = lineaScanner.next();
//                String nivelStr = lineaScanner.next(); // Tercer valor, el nivel (0 o 1)
//
//                // Verificar si el usuario y la contraseña coinciden
//                if (log.equals(txtusuario.getText()) && pass.equals(txtpassword.getText())) {
//                    nivel = Integer.parseInt(nivelStr);  // Guardar el nivel (0 o 1)
//                    break;  // Salir del bucle una vez encontrado el usuario y el nivel
//                }
//            }
//            scanner.close();
//        } catch (FileNotFoundException e) {
//            JOptionPane.showMessageDialog(null, "Archivo no encontrado: " + e.getMessage());
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
//        }
     return nivel;  // Retorna el nivel (0 o 1)
    }
    
    private void itmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUsuarioActionPerformed
        Usuarios us = new Usuarios();
        us.setVisible(true);
    }//GEN-LAST:event_itmUsuarioActionPerformed

    private void itmCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCatalogoActionPerformed
       Catalogodecuentas cc = new Catalogodecuentas();
       cc.setVisible(true);
    }//GEN-LAST:event_itmCatalogoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Movimientodetrasaccion mt = new Movimientodetrasaccion();
        mt.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CierreDiario cd = new CierreDiario();
        cd.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCatalogo;
    private javax.swing.JMenuItem itmUsuario;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JMenu menMantenimiento;
    private javax.swing.JMenu menMovimiento;
    public javax.swing.JMenu menProcesos;
    // End of variables declaration//GEN-END:variables
}
